version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres-container
    environment:
      POSTGRES_DB: librasoft
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

  web:
    image: librasoft
    container_name: librasoft-container
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5000:5000"
    volumes:
      - ./webapp:/opt/webapp
    environment:
      ConnectionStrings__DefaultConnection: ${DB_STRING_CONNECTION}
      EmailSettings__Credentials__UserName: ${EMAIL_PROVIDER_USERNAME}
      EmailSettings__Credentials__Password: ${EMAIL_PROVIDER_PASSWORD}
      EmailSettings__EmailFrom: ${EMAIL_PROVIDER_FROM}
      EmailSettings__Host: ${EMAIL_PROVIDER_HOST}
      EmailSettings__Port: ${EMAIL_PROVIDER_PORT}
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      PORT: ${PORT}
